version: 0.2

phases:
  build:
    commands:
      - sbt clean test
  post_build:
    commands:
      - sbt assembly
      - aws cloudformation package --template-file template.yaml --s3-bucket vallonde-builds
                                         --output-template-file packaged-template.yaml

artifacts:
  files:
    - target/scala-2.12/vallonde-assembly-999-SNAPSHOT.jar
    - packaged-template.yaml
