version: 0.2

env:
  variables:
    AWS_PROXY_HOST: localhost
    SERVICES: dynamodb,kinesis,s3,lambda

phases:
  install:
    commands:
      - apt-get update
      - python --version
      - apt-get install python-pip -y
      - pip --version
      - pip install localstack
      - nohup localstack start &
  build:
    commands:
      - sbt clean test it:test
      - sbt assembly lt:test

artifacts:
  files:
    - target/scala-2.12/vallonde-assembly-999-SNAPSHOT.jar
    - template.yaml
    - src/main/public/html/character.html
    - src/main/assets/js/update_character.js
