version: 0.2

env:
  variables:
    AWS_PROXY_HOST: localhost

phases:
  install:
    commands:
      - curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
      - python get-pip.py
      - pip install localstack
      - localstack start
  build:
    commands:
      - sbt clean test it:test
  post_build:
    commands:
      - sbt assembly

artifacts:
  files:
    - target/scala-2.12/vallonde-assembly-999-SNAPSHOT.jar
    - template.yaml
