swagger: 2.0
info:
  title:
    GetCharacterData
paths:
  /character/{name}:
    get:
      x-amazon-apigateway-integration:
        httpMethod: GET
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCharacterDataFunction.Arn}/invocations
      responses: {}
